version: '3'
services:
    app:
        container_name: syrius-api
        restart: always
        build: .
        environment:
            - POSTGRES_HOST=syriusdb.cluster-ct8hb1y1sm6c.us-east-1.rds.amazonaws.com
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=adot2023
            - POSTGRES_DB=syriusdb
        ports:
            - "3000:3000"