version: '3'
services:
    app:
        container_name: syrius-api
        restart: always
        build: .
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=adot2022
            - POSTGRES_DB=postgres
        ports:
            - "3000:3000"